GET http://localhost:8000/products
###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Skin Advance",
    "price": "600"
}
###
GET http://localhost:8000/products/5e8ab6f37df8771e14902af4
###
PATCH http://localhost:8000/products/5e8b7ab88466300b9c720e68
Content-Type: application/json

[
    {"propName": "name", "value": "freeplus"}
]
### 
DELETE  http://localhost:8000/products/5e8ab6f37df8771e14902af4
###

GET http://localhost:8000/orders 

###
GET http://localhost:8000/orders/5e8ccbd735fc6608a0ca576f


###
DELETE http://localhost:8000/orders/5e8ccbd735fc6608a0ca576f
###
POST http://localhost:8000/orders 
Content-Type: application/json

{
    "productID": "5e8b7ab88466300b9c720e68",
    "quantity": "10"
}

###
GET http://localhost:8000/