GET http://localhost:8000/products
###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Skin Advance",
    "price": "600"
}
###
GET http://localhost:8000/products/5e8b7ab88466300b9c720e68
###
PATCH http://localhost:8000/products/5e8b7ab88466300b9c720e68
Content-Type: application/json

[
    {"propName": "name", "value": "onePlus"}
]
### 
DELETE  http://localhost:8000/products/5e8b6230f120df2aac6d81a8
###

GET http://localhost:8000/orders 

###
GET http://localhost:8000/orders/pen

###
DELETE http://localhost:8000/orders/pen
###
POST http://localhost:8000/orders 
Content-Type: application/json

{
    "productID": "d10821040",
    "quantity": "10"
}

###
GET http://localhost:8000/